export const GET_BASKET ="GET_BASKET"
export const GET_PRODUCT ="GET_PRODUCT"

export const DECREASE_QUANTITY ="DECREASE_QUANTITY"
export const INCREASE_QUANTITY ="INCREASE_QUANTITY"

export const DELETE_FROM_BASKET ="DELETE_FROM_BASKET"